alias ga='git add .'
alias gs='git status'
alias gf='git fetch'
alias gc='git commit -m'
alias gck='git checkout'
alias gckb='git checkout -b'
alias gpull='git pull'
alias gpush='git push'
alias gdev='git checkout dev'
alias runserver='python manage.py runserver'
 
alias pdir='cd /Users/tatavo/Projetos'
